fragment PagesParts on Pages {
  ... on PagesHomepage {
    layout
    title
    text
  }
  ... on PagesAbout {
    layout
    title
    text
  }
  ... on PagesOfficial {
    layout
    title
    about_text
  }
  ... on PagesContact {
    layout
    title
    text
  }
}
