fragment PagesParts on Pages {
  ... on PagesHomepage {
    layout
    title
    text
    events {
      __typename
      date
      title
      text
      image
    }
  }
  ... on PagesAbout {
    layout
    title
    image
    about_text
  }
  ... on PagesOfficial {
    layout
    title
    nabavka {
      __typename
      date
      title
      document {
        __typename
        link
        name
      }
    }
  }
  ... on PagesContact {
    layout
    title
    image
    adress
    phone
    email
    working
    weekends
  }
}
